[mysql]
host = "localhost"
port = 3306
database = "meubanco"
user = "root"
password = "minhasenha"

[sqlserver]
host = "localhost"
port = 1433
database = "meubanco"
user = "sa"
password = "minhasenha"
